## 1. Convolutional layer

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

x = tf.random.normal((1, 28, 28, 3))
convolution = Conv2D(filters=5, kernel_size=3, strides=(1, 1), padding='valid')

convolution_result = convolution(x)
convolution_result.shape

TensorShape([1, 26, 26, 5])

In [3]:
import torch
from torch.nn import Conv2d

x = torch.randn((1, 3, 28, 28))
convolution = Conv2d(in_channels=3, out_channels=5, kernel_size=3, stride=1, padding=0)

convolution_result = convolution(x)
convolution_result.shape

torch.Size([1, 5, 26, 26])

## 2. Pooling layer

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPool2D, AveragePooling2D

max_pooling = MaxPool2D(pool_size=(2, 2), strides=(2, 2))
avg_pooling = AveragePooling2D(pool_size=(2, 2), strides=(2, 2))

x = tf.constant([
    [1., 2., 8., 4.],
    [4., 5., 6., 7.],
    [7., 8., 15., 10.],
    [11., 12., 13., 14.]
])

x = tf.reshape(x, [1, 4, 4, 1])

max_pooling_result = tf.reshape(max_pooling(x), [2, 2])
avg_pooling_result = tf.reshape(avg_pooling(x), [2, 2])

max_pooling_result, avg_pooling_result

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 5.,  8.],
        [12., 15.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 3.  ,  6.25],
        [ 9.5 , 13.  ]], dtype=float32)>)

In [5]:
import torch
from torch.nn import MaxPool2d, AvgPool2d

max_pooling = MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
avg_pooling = AvgPool2d(kernel_size=(2, 2), stride=(2, 2))

x = torch.tensor([
    [1., 2., 8., 4.],
    [4., 5., 6., 7.],
    [7., 8., 15., 10.],
    [11., 12., 13., 14.]
])

x = torch.reshape(x, (1, 4, 4))

max_pooling_result = max_pooling(x)
avg_pooling_result = avg_pooling(x)

max_pooling_result, avg_pooling_result

(tensor([[[ 5.,  8.],
          [12., 15.]]]),
 tensor([[[ 3.0000,  6.2500],
          [ 9.5000, 13.0000]]]))

## 3. Fully Сonnected layer

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Flatten, GlobalAveragePooling2D

x = tf.random.normal((1, 9, 9, 3))

x = Conv2D(filters=8, kernel_size=3)(x)
flatten = Flatten()(x)
ga_pooling = GlobalAveragePooling2D()(x)

flatten.shape, ga_pooling.shape

(TensorShape([1, 392]), TensorShape([1, 8]))

In [7]:
import torch
from torch.nn import AvgPool2d, Flatten, Conv2d

x = torch.randn(1,3,9,9)

x = Conv2d(in_channels=3, out_channels=8, kernel_size=3)(x)

pool = AvgPool2d(x.shape[2])
ga_pooling = pool(x)
ga_pooling = ga_pooling.squeeze(2).squeeze(2)
flatten = Flatten()(x)

flatten.shape, ga_pooling.shape

(torch.Size([1, 392]), torch.Size([1, 8]))

## 4. Dropout layer

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dropout

x = tf.random.normal((1, 10))
print(x)

x = Dropout(rate=0.5)(x, training=True)
print(x)

tf.Tensor(
[[ 0.4322241  -1.5245256   0.35809284  0.16722403 -1.0219539   0.453504
  -0.07137837  0.10918114 -0.95027626  1.3259474 ]], shape=(1, 10), dtype=float32)
tf.Tensor(
[[ 0.         -0.          0.          0.33444807 -2.0439079   0.
  -0.14275675  0.21836229 -0.          2.6518948 ]], shape=(1, 10), dtype=float32)


In [9]:
import torch
from torch.nn import Dropout

x = torch.randn(1, 10)
print(x)

x = Dropout(p=0.5)(x)
print(x)

tensor([[ 0.0921, -0.0851,  1.6565,  1.0936, -1.0735,  0.6137, -0.9452, -0.8641,
          0.4413,  0.0849]])
tensor([[ 0.0000, -0.0000,  3.3130,  0.0000, -0.0000,  1.2274, -0.0000, -1.7282,
          0.8826,  0.0000]])


## 5. Activation function

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, ReLU

inp = tf.random.normal((1, 5, 5, 1))
convolution = Conv2D(filters=2, kernel_size=3, strides=1, padding='valid')

output1 = convolution(inp)
relu = ReLU()
output2 = relu(output1)
output1, output2

(<tf.Tensor: shape=(1, 3, 3, 2), dtype=float32, numpy=
 array([[[[-0.5259792 ,  1.4969494 ],
          [-0.68578094, -0.26149637],
          [-0.34680468,  0.22880062]],
 
         [[-0.44417223,  2.7272906 ],
          [ 0.00824525, -0.3681308 ],
          [-0.6194949 , -1.0875105 ]],
 
         [[ 0.03927094,  0.8623146 ],
          [-0.9791769 , -1.6151513 ],
          [ 1.0513343 , -0.83749557]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3, 3, 2), dtype=float32, numpy=
 array([[[[0.        , 1.4969494 ],
          [0.        , 0.        ],
          [0.        , 0.22880062]],
 
         [[0.        , 2.7272906 ],
          [0.00824525, 0.        ],
          [0.        , 0.        ]],
 
         [[0.03927094, 0.8623146 ],
          [0.        , 0.        ],
          [1.0513343 , 0.        ]]]], dtype=float32)>)

In [11]:
import torch
from torch.nn import Conv2d, ReLU

inp = torch.randn(1, 1, 5, 5)
conv = Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0) 
output1 = conv(inp)

relu = ReLU()
output2 = relu(output1)
output1, output2

(tensor([[[[-0.0433,  0.3498,  0.7987],
           [ 0.5803,  1.1670,  0.2674],
           [ 0.0553,  0.1158,  0.2285]],
 
          [[ 0.8840,  0.2432,  0.7589],
           [-1.0698, -0.9014,  0.3136],
           [ 0.7321,  0.9454,  0.4087]]]], grad_fn=<ThnnConv2DBackward0>),
 tensor([[[[0.0000, 0.3498, 0.7987],
           [0.5803, 1.1670, 0.2674],
           [0.0553, 0.1158, 0.2285]],
 
          [[0.8840, 0.2432, 0.7589],
           [0.0000, 0.0000, 0.3136],
           [0.7321, 0.9454, 0.4087]]]], grad_fn=<ReluBackward0>))